export const SHOWS_LOADING = 'SHOWS_LOADING';
export const SHOWS_LOADED = 'SHOWS_LOADED';
export const SHOWS_ERROR = 'SHOWS_ERROR';

export const SEASONS_LOADING = 'SEASONS_LOADING';
export const SEASONS_LOADED = 'SEASONS_LOADED';
export const SEASONS_ERROR = 'SEASONS_ERROR';

export const EPISODES_LOADING = 'EPISODES_LOADING';
export const EPISODES_LOADED = 'EPISODES_LOADED';
export const EPISODES_ERROR = 'EPISODES_ERROR';

export const CAST_LOADING = 'CAST_LOADING';
export const CAST_ERROR = 'CAST_ERROR';
export const CAST_LOADED = 'CAST_LOADED';

export const IMAGES_LOADING = 'IMAGES_LOADING';
export const IMAGES_ERROR = 'IMAGES_ERROR';
export const IMAGES_LOADED = 'IMAGES_LOADED';
